name: Notificação da Tarde

on:
  schedule:
    # 3:00 PM (horário de Brasília) = 18:00 UTC
    - cron: '0 18 * * *'
  
  # Permitir execução manual
  workflow_dispatch:


jobs:
  send-afternoon-notification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Instalar dependências
        run: |
          cd backend
          npm ci
      
      - name: Configurar variáveis de ambiente
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
         
      
      - name: Enviar notificação da tarde
        run: |
          cd backend
          node scripts/send-notification.js afternoon
      
      - name: Notificar resultado
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Notificação da tarde enviada com sucesso"
          else
            echo "❌ Falha ao enviar notificação da tarde"
          fi
