name: Trigger QA Tests

on:
  push:
    branches:
      - qa

jobs:
  dispatch_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tests repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: VanderCaneppelle/buscabusca-tests
          event-type: run-tests
